### ISSUE TITLE
Deny CakeDC/Users.Users action 

### ISSUE THREAD

**Issue by tarekelasmi85** [CakeDC/cakephp-forum#1]
Hi, how can I deny the action (mywebsite/users/users )  for all users except for admin. Any idea!!
In my application everyone can access to mydomain/users/users/  even without login and delete all users. 
Thank you!

**Comment by steinkel** [comment]
You have several ways to do this, either by NOT loading the users plugin routes, using the permissions.php and RBAC to limit this page access, or adding specific rules in your AppController to block/restrict access to it.
